### ISSUE TITLE
Frames integration

### ISSUE THREAD

**Issue by o1lo01ol1o** [dpkatz/HaskellGBM#1]
integrating input-output with https://github.com/acowley/Frames would make a nice addition to the ecosystem

**Comment by dpkatz** [comment]
Yes, that's totally on the list of things to do.  :-)

**Comment by dpkatz** [comment]
So there's now some initial support for Frames - just a simple interface for converting between a `DataSet` and a `Frame`.  I'm a bit of a Frames newbie, so others will have to judge how well or poorly it works...

**Comment by dpkatz** [comment]
Re-opening.  I forgot to handle the case where the `DataSet` has no headers...

**Comment by dpkatz** [comment]
I think I've got the case where `DataSet` has no headers covered as well, now.  We just generate synthetic headers for the `Frame` (`column_0`, `column_1`, etc.).

**Comment by dpkatz** [comment]
I can't think of anything else to do with this, so I'm closing it.
